name: Terraform Plan

on:
  pull_request:

jobs:
  terraform:
    name: 'Terraform Plan'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Terraform Init
      run: terraform init

    - name: Terraform Plan
      run: terraform plan -no-color > plan.txt

    - name: Comment PR with Plan
      id: comment
      uses: marocchino/sticky-pull-request-comment@v2
      with:
        path: plan.txt
